# Generated by Django 3.2.6 on 2021-09-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_imageupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contacts',
        ),
    ]
