# Generated by Django 3.2.6 on 2021-09-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='contact',
        ),
    ]
