# Generated by Django 3.2.6 on 2021-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'manager')], default='customer', max_length=50),
        ),
    ]
