# Generated by Django 3.2.4 on 2021-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211007_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_your_user_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
