# Generated by Django 3.2.4 on 2021-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_moneytransfer_enter_your_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_your_user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
