# Generated by Django 3.2.4 on 2021-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_moneytransfer_enter_your_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
