# Generated by Django 3.2.7 on 2021-10-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_emi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.FloatField()),
                ('rate', models.FloatField()),
                ('no_of_intsallation', models.IntegerField()),
            ],
        ),
    ]
