# Generated by Django 3.2.7 on 2021-10-08 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='emi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
