# Generated by Django 3.2.8 on 2021-10-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_emi_emi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi',
            old_name='no_of_intsallation',
            new_name='no_of_intsallment',
        ),
        migrations.AddField(
            model_name='emi',
            name='Total_amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
