# Generated by Django 3.2.8 on 2021-10-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20211026_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
