# Generated by Django 3.2.8 on 2021-10-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_emi_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='type_of_loan',
            field=models.CharField(choices=[('carloan', 'carloan'), ('homeloan', 'homeloan'), ('bussinessloan', 'bussinessloan'), ('educationloan', 'educationloan')], default='carloan', max_length=50),
        ),
    ]
