# Generated by Django 3.2.8 on 2021-10-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_emi_type_of_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='emi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='no_of_intsallment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='principle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
