# Generated by Django 3.2.8 on 2021-10-26 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_auto_20211026_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emi',
            name='Total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='type_of_loan',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='user',
        ),
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('emi', models.FloatField(blank=True, null=True)),
                ('Total_amount_paid', models.FloatField(blank=True, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('type_of_loan', models.CharField(choices=[('carloan', 'carloan'), ('homeloan', 'homeloan'), ('bussinessloan', 'bussinessloan'), ('educationloan', 'educationloan')], default='carloan', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
