# Generated by Django 3.2.8 on 2021-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20211026_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='profile'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
