# Generated by Django 3.2.8 on 2021-10-27 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='user',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
