# Generated by Django 3.2.8 on 2021-10-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_emi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
