# Generated by Django 3.1.4 on 2021-10-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_bank_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
