# Generated by Django 3.1.4 on 2021-10-28 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20211027_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
