# Generated by Django 3.1.4 on 2021-10-28 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20211028_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='sender_account_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
