# Generated by Django 3.1.4 on 2021-10-28 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20211028_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
