# Generated by Django 3.1.4 on 2021-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20211028_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='sender_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
