# Generated by Django 3.1.4 on 2021-10-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_moneytransfer_receiver_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMI',
        ),
        migrations.RemoveField(
            model_name='emipayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='EMIPayment',
        ),
    ]
