# Generated by Django 3.1.4 on 2021-10-28 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0037_auto_20211028_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Complaint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='doubt',
            new_name='content',
        ),
    ]
