# Generated by Django 3.1.4 on 2021-10-29 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20211028_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
