# Generated by Django 3.1.4 on 2021-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20211029_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(),
        ),
    ]
