# Generated by Django 3.1.4 on 2021-11-08 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20211029_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='aadhar',
            field=models.IntegerField(default=123456734256),
            preserve_default=False,
        ),
    ]
