# Generated by Django 3.2.2 on 2021-11-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20211125_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='aadhar',
            field=models.CharField(max_length=50),
        ),
    ]
