# Generated by Django 3.2.6 on 2021-11-26 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_bankaccount_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
