# Generated by Django 3.2.6 on 2021-12-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_register_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
