# Generated by Django 3.2.6 on 2021-12-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_reminder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
    ]
